### ISSUE TITLE
Installed using instructions getting mapping from collections error

### ISSUE THREAD

**Issue by jaywehner** [l3uddz/plex_dupefinder#63]
**Describe the bug**
I tried installing on two different VM's running Ubuntu 22.04.1 LTS. I made sure everything was updated using apt update/upgrade. I recive the following message on both servers:

Traceback (most recent call last):
  File "/usr/local/bin/plex_dupefinder", line 11, in <module>
    from config import cfg
  File "/opt/plex_dupefinder/config.py", line 8, in <module>
    from attrdict import AttrDict
  File "/usr/local/lib/python3.10/dist-packages/attrdict/__init__.py", line 5, in <module>
    from attrdict.mapping import AttrMap
  File "/usr/local/lib/python3.10/dist-packages/attrdict/mapping.py", line 4, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**To Reproduce**
1. follow the installation instructions

**Expected behavior**
the plex_dupefinder to show the output text

You can enable debug mode by adding `--loglevel=DEBUG` to the run command.

**System Information**

 - Plex DupeFinder Version: current release as of 8/28/22
 - Operating System: Ubuntu Server 22.04.1 LTS

\* Run `git rev-parse --short HEAD` in the folder to get the GIT COMMIT ID.
COMMIT ID is 6650e39

**Comment by saltydk** [comment]
dupefinder does not support Python 3.10 yet.

**Comment by jaywehner** [comment]
What version is it supported on?

**Comment by saltydk** [comment]
Python 3.8 is probably the latest version that it supports.

**Comment by saltydk** [comment]
Should now work fine in 3.10

**Comment by jaywehner** [comment]
I re-pulled from git and still not working. I removed the original directory first. Anything else I need to do?

**Comment by saltydk** [comment]
did you install the new dependencies?

**Comment by jaywehner** [comment]
yep basically followed the instructions again. I'll try on my last VM that doesn't have it installed. And report back.

**Comment by saltydk** [comment]
Spun up a clean VM and it worked fine there.

**Comment by jaywehner** [comment]
Yep. Worked on a new install. All good! Thank you!
